name: Build and Push Container Image

on:
  push:
    branches: 
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Is Versioning Commit
        run: |
            echo "IS_VERSIONING_COMMIT=$(startsWith(github.event.commits[0].message, 'Version NFS Server Chart'))" >> $GITHUB_OUTPUT;
        id: isVersioningCommit

      - name: Get Version
        run: |
            echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_OUTPUT;
        id: version

      - if: ${{ steps.isVersioningCommit.outputs.IS_VERSIONING_COMMIT }}
        name: Tag Commit
        uses: laputansoft/github-tag-action@v4.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.version.outputs.VERSION }}

      - name: Get Tags
        run: |
            if [ ${{ steps.isVersioningCommit.outputs.isVersioningCommit }} ]; then
                tagVersion=${{ steps.version.outputs.VERSION }}
                tags="octopusdeploy/nfs-server:$tagVersion,octopusdeploy/nfs-server:latest";
            else
                tagVersion=$(git describe --tags)
                tags="octopusdeploy/nfs-server:$tagVersion,docker.packages.octopushq.com/octopusdeploy/nfs-server:$tagVersion,octopusdeploy/nfs-server:latest,docker.packages.octopushq.com/octopusdeploy/nfs-server:latest";
            fi
            echo "TAGS=$tags" >> $GITHUB_OUTPUT;
            echo "Publishing the image with the following tags: $tags";
        id: tags

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Artifactory
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ARTIFACTORY_DOCKER_REPO_HOSTNAME }}
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        

    # TODO: Uncomment this out once we've verified we are creating the right tags
    #   - name: Build and push
    #     uses: docker/build-push-action@v5
    #     with:
    #       push: true
    #       tags: ${{ steps.tags.outputs.TAGS }}
    #       platforms: linux/amd64,linux/arm64

